### ISSUE TITLE
FIX Container request hanging

### ISSUE THREAD

**Issue by Omvk97** [jakobhviid/Dashboard-Interface-Docker#9]
Often when sending a request to a container it will be done, but the UI does not recieve a response from Dashboard-Server. This makes the UI loader hang

**Comment by Omvk97** [comment]
Instead of having a dedicated response topic, it would be better to only have overview and stat channels and include a status and message attribute in the JSON response from Dashboard Server

**Comment by dstoft** [comment]
Eureka! I'm quite confident that I discovered the bug. The issue was early on identified to be the Socketserver not "receiving" the latest events on the "command-responses-" topic.
The socket server looks for the reponse topics using a prefix. It looks for all the topics starting with "command-responses-", and the dashboard servers emit "command-responses-{Servername}-{SelfContainerId}". However, I believe it only looks once, when the consumer i created, at what topics contains this prefix. That means, if the topic is created after the consumer is created, then the consumer never realize that the new "reponse topic" exists.

I'm still unsure of how to properly fix this. The solution proposed by Omvk97, but regardless of what solution is decided upon, it will require quite a bit of work. I'll discuss this with Mads.

**Comment by dstoft** [comment]
After having played around with the consumer and threading in the socket server, I cannot find a way to "restart" the consumer and its thread with an updated list of topics to subscribe on. The closest I got was updating the assignments of the consumer, which takes effect immediatly, however, there appeared to be no way to gracefully stop the consumer's task of consuming.
This means I'm now leaning towards starting a "fresh" consumer everytime a command request is issued, and then limiting the Consume task to 5 or 10 seconds, and simply terminate afterwards, as the "result" would be too late for the user anways. The UI could show an error, and allow the user to "reissue" the request. The consumer would listen to only the correct topic.

On a side now, I'm not sure that I agree on the removal of cmd responses topic as a concept, as it would leave commands such as rename, restart, etc. without a response.

**Comment by dstoft** [comment]
After a conversation with @mads5606 I will now attempt to implement a "fresh" consumer of the response topic every time a request command is issued instead of the background service currently implemented.

**Comment by dstoft** [comment]
During the process of implementing a fresh consumer, I ended up finding a way to get the "status" of the current consumer, and therefore know when it should be restarted and when it subscribes to the right topics. This means that I changed the plan back to a background worker, that only restarts gracefully when a subscription topic is new, or else it runs as usual. It appears to be working, however, there is a slight issue. Background workers are supposed to be "forgotten" after they have been setup, therefore I turned it into a "singleton", but it is not great code practice to do so. Therefore I will discuss the setup with Mads before creating a pull request.
The current implementation is located at: https://github.com/jakobhviid/Dashboard-Interface-Docker/tree/feature/issue-9-response-topic-bug

**Comment by dstoft** [comment]
After a brief discussion with Mads, it was agreed that a simple solution is prefered over a complicated one. Therefore the background service instance remains available as singleton, eventhough this is not the intention of a background service.

I have wrapped up the fixes in a pull request. The final implementation allows the background service with the Kafka consumer (running in its own async task) to be cancelled and started again. When it is started again, it will use the updated list of the subscription topics. It is only possible to add to this list for now, as there is no use for removing topics again at the moment.
The methods outside of the background service, can use a simple method to check whether the topic is currently being subscribed to. If the topic is not subscribed to, it will update the list of desired topics and then "restart" the consumer.
